services:
    werkint.webapp:
        class: Werkint\Bundle\WebappBundle\Webapp\Webapp
        arguments:
            - @werkint.webapp.scriptloader
    werkint.webapp.scriptloader:
        class: Werkint\Bundle\WebappBundle\Webapp\ScriptLoader
        arguments:
            - %kernel.debug%
            - %appmode%
    werkint.webapp.compiler:
        class: Werkint\Bundle\WebappBundle\Webapp\Compiler
        arguments:
            - %werkint_webapp%
            - %kernel.debug%
        tags:
            - { name: kernel.cache_clearer, priority: 0 }
    werkint.webapp.browsercheck:
        class: Werkint\Bundle\WebappBundle\Webapp\BrowserCheck
        scope: request
        arguments:
            - @request
            - %werkint_webapp.browsers%

    werkint.webapp.listener.template:
        class: Werkint\Bundle\WebappBundle\EventListener\Template
        arguments:
            - @werkint.webapp.scriptloader
        tags:
            - { name: kernel.event_listener, event: werkint.webapp.displaypost, method: templateDisplayPost }
            - { name: kernel.event_listener, event: werkint.webapp.blockpre, method: templateBlockStart }
            - { name: kernel.event_listener, event: werkint.webapp.blockpost, method: templateBlockEnd }
    werkint.webapp.listener.viewinjector:
        class: Werkint\Bundle\WebappBundle\EventListener\ViewInjector
        arguments:
            - @templating.engine.twig
            - @werkint.webapp.scriptloader
            - @werkint.webapp.compiler
            - %werkint_webapp%
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    werkint.webapp.listener.browserwarninjector:
        class: Werkint\Bundle\WebappBundle\EventListener\BrowserWarnInjector
        scope: request
        arguments:
            - @templating.engine.twig
            - @werkint.webapp.browsercheck
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    werkint.webapp.listener.ajaxredirect:
        class: Werkint\Bundle\WebappBundle\EventListener\AjaxRedirect
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    werkint.webapp.listener.request:
        class: Werkint\Bundle\WebappBundle\EventListener\Request
        arguments:
            - @werkint.webapp.scriptloader
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest, priority: -10 }
    werkint.webapp.listener.ajaxexception:
        class: Werkint\Bundle\WebappBundle\EventListener\AjaxException
        arguments:
            - %kernel.debug%
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    werkint.webapp.listener.ajaxfilter:
        class: Werkint\Bundle\WebappBundle\EventListener\AjaxFilter
        arguments:
            - @router
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    werkint.webapp.listener.twigextension:
        class: Werkint\Bundle\WebappBundle\Twig\Extension\Extension
        arguments:
            - @werkint.webapp.scriptloader
            - @event_dispatcher
        tags:
            -  { name: twig.extension }
    # AJAX login exception
    werkint.webapp.listener.authhandler:
        class: Werkint\Bundle\WebappBundle\EventListener\AuthHandler
        arguments:
            - @form.csrf_provider
            - @translator
