services:
    twig.loader:
        class: Werkint\Bundle\WebAppBundle\WebApp\Twig\Loader
        arguments: [false]
    werkint.webappbundle.webapp:
        class: Werkint\Bundle\WebAppBundle\WebApp\WebApp
        tags:
            - { name: templating.helper }
            - { name: kernel.event_listener, event: werkint.twig.postconstruct, method: templateConstruct }
        arguments: [@service_container, @event_dispatcher]